spring.application.name=InternHub

# Server
server.port=8080

# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/internhub
spring.datasource.username=admin
spring.datasource.password=admin321
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA: doesn't create tables automatically, just verifies the schema from Flyway
# Could be set to - 'update': auto-changes schema to match entities
#                 - 'create / create-drop': drops and recreates the schema on startup, which would lead to data loss
#                 - 'validate': checks if the schema matches the entities, but doesn't modify it (recommended for production)
spring.jpa.hibernate.ddl-auto=validate

# Flyway migrations
spring.flyway.locations=classpath:db/migration

spring.flyway.enabled=true

# Validate that migration files follow the naming convention (e.g., V1__Initial.sql)
# If set to true, Flyway will throw an error if any migration files do not follow the naming convention
spring.flyway.validate-migration-naming=true

app.azure.connection-string=${AZURE_STORAGE_CONNECTION_STRING:DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;}
app.azure.container=cvs

logging.level.com.azure=INFO

# File upload limits so that users cannot upload excessively large files that could cause performance issues or exhaust server resources
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Include error messages in the response body for easier debugging during development.
# In production, this should be set to 'never' to avoid exposing sensitive information.
spring.web.error.include-message=always